version: '3.1'
services:
  nginx:
    build: .
    #  context: ./nginx
    image: final-project-image:v1
    container_name: final-project-container
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=jamilaali.com
    depends_on:
      - mysql
   # volumes:
   #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   #  - ./nginx.conf:/etc/nginx/nginx.conf  
   #   - ./html/:/usr/share/nginx/html/
   #  - /srv/:/srv/
    networks:
      - my-network

  mysql:
#    platform: linux/x86_64
    image: mysql:8.0.34
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
  #  driver: bridge

#volumes:
#  mysql-data:

